// messages.js
export const ErrorMessage = {
  MSG1: "You must specify a value for this required field.",
  MSG2: "Passwords do not match",
  MSG3: "Invalid email format",
  MSG4: "Email already registered",
  MSG5: "Password is too weak",
  MSG6: "Invalid format username",
  MSG7: "Invalid or already taken username.",
  MSG8: "Verification email sending failed",
  MSG9: "Invalid or expired verification code",
  MSG10: "Validated email successful",
  MSG11: "Invalid username or password",
  MSG12: "Account is inactive or locked",
  MSG13: "Failed to delete token from Local Storage",
  MSG14: "Logout successfully",
  MSG15: "Logout failed",
  MSG16: "Email or username already taken",
  MSG18: "Your progress may not have been fully saved.",
  MSG19: "No vocabulary due for review.",
  MSG20: "Correct!",
  MSG21: "No posts available",
  MSG22: "No folders available",
  MSG23: "Price must be a number and greater than 0",
  MSG24: "Payment successful",
  MSG25: "Payment failed. Please try again.",
  MSG26: "Invalid amount",
  MSG27: "Amount cannot greater than balance",
  MSG28: "Request withdraw successfully",
};
